var
/** @define {boolean} */
    DEFINE_HTML2JSON__EXPORT_JSON2HTML = false,
/** @define {boolean} */
    DEFINE_HTML2JSON__EXPORT_JSON2JSON = false,
/** @define {boolean} */
    DEFINE_HTML2JSON__DEBUG            = false,
/** @define {boolean} */
    DEFINE_HTML2JSON__USE_XML_NS       = true,
/** @define {boolean} */
    DEFINE_HTML2JSON__USE_XHTML        = true,
/** @define {boolean} */
    DEFINE_HTML2JSON__GULP_PULGIN      = false;

/** @define {string} */
var DEFINE_HTML2JSON__INSTRUCTION_ATTR_PREFIX = ':';

/**
 * @enum {number}
 */
var HTML_DOT_JSON__NODE_TYPE = {
    ELEMENT_NODE                   :  1, // v
    // ATTRIBUTE_NODE                 2
    TEXT_NODE                      :  3, // v
    CDATA_SECTION                  :  4, // v
    // EntityReference                5
    // Entity                         6
    PROCESSING_INSTRUCTION         :  7, // v
    COMMENT_NODE                   :  8, // v
    DOCUMENT_NODE                  :  9, // v
    // DOCUMENT_TYPE_NODE            10
    DOCUMENT_FRAGMENT_NODE         : 11, // v
    // Notation                      12
    CONDITIONAL_COMMENT_HIDE_LOWER : 13,
    CONDITIONAL_COMMENT_SHOW_LOWER : 14,
    NETSCAPE4_CONDITIONAL_COMMENT  : 15
};

/**
 * @enum {number}
 */
const DEFINE_HTML2JSON__PHASE = {
    ERROR                          : HTML_DOT_JSON__NODE_TYPE.ELEMENT_NODE - 2,
    NODE_START                     : HTML_DOT_JSON__NODE_TYPE.ELEMENT_NODE - 1,

    ELEMENT_NODE_START             : HTML_DOT_JSON__NODE_TYPE.ELEMENT_NODE,
    TEXT_NODE_START                : HTML_DOT_JSON__NODE_TYPE.TEXT_NODE,
    CDATA_SECTION_START            : HTML_DOT_JSON__NODE_TYPE.CDATA_SECTION,
    PROCESSING_INSTRUCTION_START   : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION,
    COMMENT_NODE_START             : HTML_DOT_JSON__NODE_TYPE.COMMENT_NODE,
    DOCUMENT_NODE_START            : HTML_DOT_JSON__NODE_TYPE.DOCUMENT_NODE,
    DOCUMENT_FRAGMENT_NODE_START   : HTML_DOT_JSON__NODE_TYPE.DOCUMENT_FRAGMENT_NODE,
    COMMENT_HIDE_LOWER_START       : HTML_DOT_JSON__NODE_TYPE.CONDITIONAL_COMMENT_HIDE_LOWER,
    COMMENT_SHOW_LOWER_START       : HTML_DOT_JSON__NODE_TYPE.CONDITIONAL_COMMENT_SHOW_LOWER,
    NETSCAPE4_CONDITIONAL_COMMENT  : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT,
    // <-- copy to EXPECT
    DOCUMENT_NODE_VALUE            : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT +  1,
    TEXT_NODE_VALUE                : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT +  2,
    CDATA_SECTION_VALUE            : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT +  3,
    COMMENT_NODE_VALUE             : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT +  4,
    COMMENT_HIDE_LOWER_FORMURA     : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT +  5,
    COMMENT_SHOW_LOWER_FORMURA     : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT +  6,
    PROCESSING_INSTRUCTION_NAME    : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT +  7,

    TAG_NAME                       : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT +  8,

    ATTRIBUTES_START               : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT +  9,
    ATTRIBUTE_PROPERTY             : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 10,
    ATTRIBUTE_VALUE                : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 11,

    STYLES_START                   : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 12,
    CSS_PROPERTY                   : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 13,
    CSS_VALUE                      : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 14,
    
    IN_INSTRUCTION_ATTRIBUTE       : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 15,

    END_OF_NODE                    : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 16,
    // copy to EXPECT -->
    CLOSE_EMPTY_ELEMENT            : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 17,
    END_OF_ATTRIBUTES              : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 18,
    END_OF_STYLES                  : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 19,
    TEXT_DATA                      : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 20,
    INSTRUCTION_ATTRIBUTE_NAME     : HTML_DOT_JSON__NODE_TYPE.NETSCAPE4_CONDITIONAL_COMMENT + 21
};

/**
 * @enum {number}
 */
const DEFINE_HTML2JSON__EXPECT = {
    // <-- copy from PHASE
    ERROR                          : DEFINE_HTML2JSON__PHASE.ERROR,
    NODE_START                     : DEFINE_HTML2JSON__PHASE.NODE_START,

    DOCUMENT_NODE_VALUE            : DEFINE_HTML2JSON__PHASE.DOCUMENT_NODE_VALUE, //
    TEXT_NODE_VALUE                : DEFINE_HTML2JSON__PHASE.TEXT_NODE_VALUE, //
    CDATA_SECTION_VALUE            : DEFINE_HTML2JSON__PHASE.CDATA_SECTION_VALUE,
    COMMENT_NODE_VALUE             : DEFINE_HTML2JSON__PHASE.COMMENT_NODE_VALUE, //
    COMMENT_HIDE_LOWER_FORMURA     : DEFINE_HTML2JSON__PHASE.COMMENT_HIDE_LOWER_FORMURA, //
    COMMENT_SHOW_LOWER_FORMURA     : DEFINE_HTML2JSON__PHASE.COMMENT_SHOW_LOWER_FORMURA, //
    PROCESSING_INSTRUCTION_NAME    : DEFINE_HTML2JSON__PHASE.PROCESSING_INSTRUCTION_NAME, //

    TAG_NAME                       : DEFINE_HTML2JSON__PHASE.TAG_NAME, //

    ATTRIBUTES_START               : DEFINE_HTML2JSON__PHASE.ATTRIBUTES_START, //
    ATTRIBUTE_PROPERTY             : DEFINE_HTML2JSON__PHASE.ATTRIBUTE_PROPERTY,
    ATTRIBUTE_VALUE                : DEFINE_HTML2JSON__PHASE.ATTRIBUTE_VALUE,

    STYLES_START                   : DEFINE_HTML2JSON__PHASE.STYLES_START,
    CSS_PROPERTY                   : DEFINE_HTML2JSON__PHASE.CSS_PROPERTY, //
    CSS_VALUE                      : DEFINE_HTML2JSON__PHASE.CSS_VALUE, //

    IN_INSTRUCTION_ATTRIBUTE       : DEFINE_HTML2JSON__PHASE.IN_INSTRUCTION_ATTRIBUTE,

    END_OF_NODE                    : DEFINE_HTML2JSON__PHASE.END_OF_NODE, //
    // copy from PHASE -->
    NODE_TYPE                      : DEFINE_HTML2JSON__PHASE.END_OF_NODE + 1,
    PROCESSING_INSTRUCTION_ARGS    : DEFINE_HTML2JSON__PHASE.END_OF_NODE + 2,
    INSTRUCTION_ATTRIBUTE_START    : DEFINE_HTML2JSON__PHASE.END_OF_NODE + 3,
    CHILD_NODES_START              : DEFINE_HTML2JSON__PHASE.END_OF_NODE + 4,
    IN_CHILD_NODES                 : DEFINE_HTML2JSON__PHASE.END_OF_NODE + 5,
    END_OF_DOCUMENT                : DEFINE_HTML2JSON__PHASE.END_OF_NODE + 6
};

