var
/** @define {boolean} */
    DEFINE_HTML2JSON__EXPORT_JSON2HTML = false,
/** @define {boolean} */
    DEFINE_HTML2JSON__EXPORT_JSON2JSON = false,
/** @define {boolean} */
    DEFINE_HTML2JSON__DEBUG            = false,
/** @define {boolean} */
    DEFINE_HTML2JSON__USE_XML_NS       = true,
/** @define {boolean} */
    DEFINE_HTML2JSON__USE_XHTML        = true;

/** @define {string} */
var DEFINE_INSTRUCTION_ATTR_PREFIX     = ':';

/**
 * @enum {number}
 */
var HTML_DOT_JSON__NODE_TYPE = {
    DOCUMENT_NODE                  : 0, // <- 10
    DOCUMENT_FRAGMENT_NODE         : 1, // <- 11
    ELEMENT_NODE                   : 2, // <-  1
    TEXT_NODE                      : 3,
    COMMENT_NODE                   : 4, // <-  8
    CONDITIONAL_COMMENT_HIDE_LOWER : 5,
    CONDITIONAL_COMMENT_SHOW_LOWER : 6,
    PROCESSING_INSTRUCTION         : 7
};

/**
 * @enum {number}
 */
const EXPECT = {
    ERROR                          : HTML_DOT_JSON__NODE_TYPE.DOCUMENT_NODE - 2,
    NODE_START                     : HTML_DOT_JSON__NODE_TYPE.DOCUMENT_NODE - 1,

    DOCUMENT_NODE_VALUE            : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION +  1,
    TEXT_NODE_VALUE                : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION +  2,
    COMMENT_NODE_VALUE             : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION +  3,
    COMMENT_HIDE_LOWER_FORMURA     : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION +  4,
    COMMENT_SHOW_LOWER_FORMURA     : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION +  5,
    PROCESSING_INSTRUCTION_NAME    : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION +  6,

    TAG_NAME                       : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION +  7,

    ATTRIBUTES_START               : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION +  8,
    ATTRIBUTE_PROPERTY             : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION +  9,
    ATTRIBUTE_VALUE                : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 10,

    STYLES_START                   : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 11,
    CSS_PROPERTY                   : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 12,
    CSS_VALUE                      : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 13,
    
    IN_INSTRUCTION_ATTRIBUTE       : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 14,

    END_OF_NODE                    : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 15,

    NODE_TYPE                      : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 16,
    PROCESSING_INSTRUCTION_ARGS    : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 17,
    INSTRUCTION_ATTRIBUTE_START    : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 18,
    CHILD_NODES_START              : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 19,
    IN_CHILD_NODES                 : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 20,
    END_OF_DOCUMENT                : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION + 21
};

/**
 * @enum {number}
 */
const PHASE = {
    ERROR                          : EXPECT.ERROR,
    NODE_START                     : EXPECT.NODE_START,//

    DOCUMENT_NODE_START            : HTML_DOT_JSON__NODE_TYPE.DOCUMENT_NODE, //
    DOCUMENT_FRAGMENT_NODE_START   : HTML_DOT_JSON__NODE_TYPE.DOCUMENT_FRAGMENT_NODE, //
    ELEMENT_NODE_START             : HTML_DOT_JSON__NODE_TYPE.ELEMENT_NODE, //
    TEXT_NODE_START                : HTML_DOT_JSON__NODE_TYPE.TEXT_NODE, //
    COMMENT_NODE_START             : HTML_DOT_JSON__NODE_TYPE.COMMENT_NODE, //
    COMMENT_HIDE_LOWER_START       : HTML_DOT_JSON__NODE_TYPE.CONDITIONAL_COMMENT_HIDE_LOWER, //
    COMMENT_SHOW_LOWER_START       : HTML_DOT_JSON__NODE_TYPE.CONDITIONAL_COMMENT_SHOW_LOWER, //
    PROCESSING_INSTRUCTION_START   : HTML_DOT_JSON__NODE_TYPE.PROCESSING_INSTRUCTION, //

    DOCUMENT_NODE_VALUE            : EXPECT.DOCUMENT_NODE_VALUE, //
    TEXT_NODE_VALUE                : EXPECT.TEXT_NODE_VALUE, //
    COMMENT_NODE_VALUE             : EXPECT.COMMENT_NODE_VALUE, //
    COMMENT_HIDE_LOWER_FORMURA     : EXPECT.COMMENT_HIDE_LOWER_FORMURA, //
    COMMENT_SHOW_LOWER_FORMURA     : EXPECT.COMMENT_SHOW_LOWER_FORMURA, //
    PROCESSING_INSTRUCTION_NAME    : EXPECT.PROCESSING_INSTRUCTION_NAME, //

    TAG_NAME                       : EXPECT.TAG_NAME, //

    ATTRIBUTES_START               : EXPECT.ATTRIBUTES_START, //
    ATTRIBUTE_PROPERTY             : EXPECT.ATTRIBUTE_PROPERTY,
    ATTRIBUTE_VALUE                : EXPECT.ATTRIBUTE_VALUE,

    STYLES_START                   : EXPECT.STYLES_START,
    CSS_PROPERTY                   : EXPECT.CSS_PROPERTY, //
    CSS_VALUE                      : EXPECT.CSS_VALUE, //

    IN_INSTRUCTION_ATTRIBUTE       : EXPECT.IN_INSTRUCTION_ATTRIBUTE,

    END_OF_NODE                    : EXPECT.END_OF_NODE, //

    CLOSE_EMPTY_ELEMENT            : EXPECT.END_OF_NODE + 1, //
    END_OF_ATTRIBUTES              : EXPECT.END_OF_NODE + 2, //
    END_OF_STYLES                  : EXPECT.END_OF_NODE + 3, //
    TEXT_DATA                      : EXPECT.END_OF_NODE + 4, //
    INSTRUCTION_ATTRIBUTE_NAME     : EXPECT.END_OF_NODE + 5
};
